In [1]:
import numpy as np
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [3]:
from keras.layers import TextVectorization

In [8]:
vectorization = TextVectorization(
    max_tokens=10000,
    output_mode='int',
)

In [9]:
vectorization.adapt(docs)

In [10]:
vectorization_text = vectorization(docs)

In [11]:
print(vectorization_text)

tf.Tensor(
[[16  2  0  0  0]
 [ 2  2  0  0  0]
 [ 8  8 15  0  0]
 [ 3 18  3  2  3]
 [17 12  6  7  0]
 [ 5  5  0  0  0]
 [ 4  4  0  0  0]
 [ 9  9  0  0  0]
 [11 13  6  7  0]
 [14 10  0  0  0]], shape=(10, 5), dtype=int64)


In [15]:
vectorization.get_vocabulary()

['',
 '[UNK]',
 np.str_('india'),
 np.str_('jeetega'),
 np.str_('sachin'),
 np.str_('kohli'),
 np.str_('ki'),
 np.str_('jai'),
 np.str_('hip'),
 np.str_('dhoni'),
 np.str_('zindabad'),
 np.str_('modi'),
 np.str_('mata'),
 np.str_('ji'),
 np.str_('inquilab'),
 np.str_('hurray'),
 np.str_('go'),
 np.str_('bharat'),
 np.str_('bhai')]

In [21]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,Flatten,Embedding,SimpleRNN
from keras.utils import pad_sequences

In [17]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 7s 0us/step


In [18]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [19]:
X_train.shape

(25000,)

In [22]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [24]:
model = Sequential([
    SimpleRNN(32,input_shape=(50,1),return_sequences=False),
    Dense(1,activation='sigmoid')
])

In [25]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5


2026-03-03 18:21:48.747651: I external/local_xla/xla/service/service.cc:163] XLA service 0x7f8d840d6300 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-03-03 18:21:48.747671: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 6GB Laptop GPU, Compute Capability 8.6
2026-03-03 18:21:48.771962: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-03-03 18:21:48.863413: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91002


 44/782 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5146 - loss: 0.7250

I0000 00:00:1772542309.292757   20610 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.5057 - loss: 0.6942 - val_accuracy: 0.5028 - val_loss: 0.6954
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5028 - loss: 0.6935 - val_accuracy: 0.5032 - val_loss: 0.6954
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4997 - loss: 0.6935 - val_accuracy: 0.5029 - val_loss: 0.6947
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.5102 - loss: 0.6925 - val_accuracy: 0.5036 - val_loss: 0.6946
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.5059 - loss: 0.6930 - val_accuracy: 0.5063 - val_loss: 0.6938


In [29]:
model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


array([[0.50882995],
       [0.50882995],
       [0.50882995],
       ...,
       [0.50882995],
       [0.50883   ],
       [0.50882995]], shape=(25000, 1), dtype=float32)