In [1]:
import numpy as np

docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']


In [2]:
from keras.layers import TextVectorization

vectorization = TextVectorization(
    max_tokens=10000,
    output_mode='int',
)


I0000 00:00:1774556787.499529  674282 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1774556787.529050  674282 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1774556788.176193  674282 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
W0000 00:00:1774556789.005087  674282 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries men

In [3]:
vectorization.adapt(docs)
vectorization_text = vectorization(docs)
print(vectorization_text)

tf.Tensor(
[[16  2  0  0  0]
 [ 2  2  0  0  0]
 [ 8  8 15  0  0]
 [ 3 18  3  2  3]
 [17 12  6  7  0]
 [ 5  5  0  0  0]
 [ 4  4  0  0  0]
 [ 9  9  0  0  0]
 [11 13  6  7  0]
 [14 10  0  0  0]], shape=(10, 5), dtype=int64)


In [4]:
vectorization.get_vocabulary()

['',
 '[UNK]',
 np.str_('india'),
 np.str_('jeetega'),
 np.str_('sachin'),
 np.str_('kohli'),
 np.str_('ki'),
 np.str_('jai'),
 np.str_('hip'),
 np.str_('dhoni'),
 np.str_('zindabad'),
 np.str_('modi'),
 np.str_('mata'),
 np.str_('ji'),
 np.str_('inquilab'),
 np.str_('hurray'),
 np.str_('go'),
 np.str_('bharat'),
 np.str_('bhai')]

In [5]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, Flatten, Embedding, SimpleRNN
from keras.utils import pad_sequences

In [6]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [7]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [21]:
model = Sequential([
    Embedding(100000,64,input_length=100)
])

In [22]:
model.add(SimpleRNN(32))
model.add(Dense(1,activation='sigmoid'))

In [23]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5


782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 21ms/step - accuracy: 0.7307 - loss: 0.5168 - val_accuracy: 0.7920 - val_loss: 0.4463
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 21ms/step - accuracy: 0.8934 - loss: 0.2659 - val_accuracy: 0.7995 - val_loss: 0.4880
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 21ms/step - accuracy: 0.9672 - loss: 0.1006 - val_accuracy: 0.7908 - val_loss: 0.5939
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 21ms/step - accuracy: 0.9912 - loss: 0.0319 - val_accuracy: 0.7589 - val_loss: 0.7961
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 21ms/step - accuracy: 0.9954 - loss: 0.0186 - val_accuracy: 0.7716 - val_loss: 0.8369


In [14]:
y_preds = model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step


In [16]:
y_test

array([0, 1, 1, ..., 0, 0, 0], shape=(25000,))

In [17]:
pred_labels = (y_preds > 0.5).astype(int)

In [19]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_test,pred_labels)

0.73904