In [1]:
import numpy as np

docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inquilab zindabad']


In [2]:
from keras.layers import TextVectorization

vectorization = TextVectorization(
    max_tokens=10000,
    output_mode='int',
)


2026-03-03 18:35:30.088691: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-03 18:35:30.119168: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-03 18:35:30.846222: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1772543131.258736   23868 gpu_device.cc:2020] Created device /job:localhost/rep

In [3]:
vectorization.adapt(docs)
vectorization_text = vectorization(docs)
print(vectorization_text)

tf.Tensor(
[[16  2  0  0  0]
 [ 2  2  0  0  0]
 [ 8  8 15  0  0]
 [ 3 18  3  2  3]
 [17 12  6  7  0]
 [ 5  5  0  0  0]
 [ 4  4  0  0  0]
 [ 9  9  0  0  0]
 [11 13  6  7  0]
 [14 10  0  0  0]], shape=(10, 5), dtype=int64)


In [4]:
vectorization.get_vocabulary()

['',
 '[UNK]',
 np.str_('india'),
 np.str_('jeetega'),
 np.str_('sachin'),
 np.str_('kohli'),
 np.str_('ki'),
 np.str_('jai'),
 np.str_('hip'),
 np.str_('dhoni'),
 np.str_('zindabad'),
 np.str_('modi'),
 np.str_('mata'),
 np.str_('ji'),
 np.str_('inquilab'),
 np.str_('hurray'),
 np.str_('go'),
 np.str_('bharat'),
 np.str_('bhai')]

In [5]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, Flatten, Embedding, SimpleRNN
from keras.utils import pad_sequences

In [6]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [7]:
X_train = pad_sequences(X_train, padding='post', maxlen=50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [8]:
model = Sequential()

In [9]:
model.add(Embedding(10000,64,input_length=100))
model.add(SimpleRNN(32))
model.add(Dense(1,activation='sigmoid'))

/home/enky-yy/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5


2026-03-03 18:36:08.961680: I external/local_xla/xla/service/service.cc:163] XLA service 0x7f9b38004b70 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-03-03 18:36:08.961693: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 6GB Laptop GPU, Compute Capability 8.6
2026-03-03 18:36:08.979515: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-03-03 18:36:09.077217: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91002


 27/782 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.5100 - loss: 0.6979

I0000 00:00:1772543169.609415   23970 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.7620 - loss: 0.4879 - val_accuracy: 0.7956 - val_loss: 0.4449
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8564 - loss: 0.3337 - val_accuracy: 0.7949 - val_loss: 0.4644
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9350 - loss: 0.1753 - val_accuracy: 0.7727 - val_loss: 0.5693
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9788 - loss: 0.0675 - val_accuracy: 0.7686 - val_loss: 0.7502
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9908 - loss: 0.0335 - val_accuracy: 0.7390 - val_loss: 0.9054


In [14]:
y_preds = model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step


In [16]:
y_test

array([0, 1, 1, ..., 0, 0, 0], shape=(25000,))

In [17]:
pred_labels = (y_preds > 0.5).astype(int)

In [19]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_test,pred_labels)

0.73904