In [1]:
import numpy as np
from distributed.utils_test import padded_time

faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [2]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS']='0'
import tensorflow
from keras.layers import TextVectorization

2026-03-04 21:11:50.684660: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
vectorization = TextVectorization()

I0000 00:00:1772638912.241683  476469 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4174 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


In [4]:
vectorization.adapt(faqs.split('\n'))

In [6]:
vocab_size=len(vectorization.get_vocabulary())

In [7]:
input_seq=[]

for sentence in faqs.split('\n'):
    content = vectorization(sentence)

    for i in range (1,len(content)):
        n_gram = content[:i+1]
        input_seq.append(n_gram)

In [43]:
 input_seq23 = vectorization(faqs.split('\n'))

In [44]:
input_seq23

<tf.Tensor: shape=(78, 57), dtype=int64, numpy=
array([[137,   2,  14, ...,   0,   0,   0],
       [ 12,   8,   2, ...,   0,   0,   0],
       [  2,  13, 122, ...,   0,   0,   0],
       ...,
       [ 16,  87, 213, ...,   0,   0,   0],
       [234,  17, 208, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], shape=(78, 57))>

In [8]:
input_seq

[<tf.Tensor: shape=(2,), dtype=int64, numpy=array([137,   2])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([137,   2,  14])>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([12,  8])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([12,  8,  2])>,
 <tf.Tensor: shape=(4,), dtype=int64, numpy=array([12,  8,  2, 13])>,
 <tf.Tensor: shape=(5,), dtype=int64, numpy=array([12,  8,  2, 13, 48])>,
 <tf.Tensor: shape=(6,), dtype=int64, numpy=array([12,  8,  2, 13, 48, 15])>,
 <tf.Tensor: shape=(7,), dtype=int64, numpy=array([12,  8,  2, 13, 48, 15, 57])>,
 <tf.Tensor: shape=(8,), dtype=int64, numpy=array([12,  8,  2, 13, 48, 15, 57, 68])>,
 <tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 12,   8,   2,  13,  48,  15,  57,  68, 113])>,
 <tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 12,   8,   2,  13,  48,  15,  57,  68, 113,  14])>,
 <tf.Tensor: shape=(11,), dtype=int64, numpy=array([ 12,   8,   2,  13,  48,  15,  57,  68, 113,  14, 230])>,
 <tf.Tensor: shape=(12,), dtype=int

In [9]:
max_len=max([len(x) for x in input_seq])

In [10]:
from keras.preprocessing.sequence import pad_sequences

In [11]:
padded_input_seq=pad_sequences(input_seq, maxlen=max_len, padding='pre')

In [12]:
padded_input_seq

array([[  0,   0,   0, ...,   0, 137,   2],
       [  0,   0,   0, ..., 137,   2,  14],
       [  0,   0,   0, ...,   0,  12,   8],
       ...,
       [  0,   0,   0, ..., 234,  17, 208],
       [  0,   0,   0, ...,  17, 208, 214],
       [  0,   0,   0, ..., 208, 214, 156]], shape=(824, 57), dtype=int32)

In [13]:
x = padded_input_seq[:,:-1]

In [14]:
x.shape

(824, 56)

In [15]:
y = padded_input_seq[:,-1]
y

array([  2,  14,   8,   2,  13,  48,  15,  57,  68, 113,  14, 230, 274,
        13, 122,   7,  45,  33, 109,  31,   3,   9,   5,  28,  45,  70,
         6,  36, 266,   8,   2,  63,  79,   6,   2,  13,  63,  79,   6,
         2,  13,   8,  84,  73,  34,   2,  63,  13,  48, 252, 267,  36,
       270,   8,   2,  92,   6,   2, 113,  14,  10,  22, 241,   2, 222,
       189, 221, 201,  15,  57,  68, 262,  15,  57,  68,  15, 197,  74,
       264, 110,  95,  11, 245,   2, 236,  92,  77, 215, 126,  74,  23,
       107,  22,   7,  71,   6,  20,  14, 107,  23, 126,  74, 250,  61,
        44,   7,  71,   6,  20, 176, 237,  21,   4, 111,   7, 115,  35,
        10,   4,  47,   7, 100,   6,   2,  35,  19,  39,  16,  61, 170,
        34, 123,  21,   3, 111,   7,  35,   3,  11, 220, 256,  23,  51,
         2, 100,  11,   4, 223,   2, 131, 167,  20,  78, 164,   5,  67,
        53,  59,  53,  91, 155,   6,   2,  13, 217,   8,   2,  91,  79,
         6,  19,   2, 115,  16,  19,   2,  16, 203, 139, 218,   

In [16]:
y.shape

(824,)

In [17]:
from keras.utils import to_categorical
y = to_categorical(y,num_classes=vocab_size)

In [18]:
from keras import Sequential
from keras.layers import  Dense , LSTM,Embedding

In [21]:
model = Sequential([
    Embedding(vocab_size,100,input_length=max_len-1),
    LSTM(150),
    Dense(vocab_size,activation='softmax')
])

In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [24]:
model.fit(x, y,epochs=100)

Epoch 1/100


2026-03-04 21:13:27.659349: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91002


26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0704 - loss: 5.4212
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0813 - loss: 5.0486
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0813 - loss: 4.9679
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0813 - loss: 4.9246
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0813 - loss: 4.8624
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0874 - loss: 4.7617
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0947 - loss: 4.6410
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1371 - loss: 4.4590
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1663 - loss: 4.2444
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1978 - loss: 4.0239
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2306 - loss: 3.7851
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2391 - lo

In [40]:
import time
text = 'what is the course fee'

for i in range(10):
    token_text = vectorization(text)

    padd_token_seq = pad_sequences([token_text], maxlen=max_len,padding='pre')

    preds = np.argmax(model.predict(padd_token_seq))

    for word in vectorization.get_vocabulary():
        if (vectorization.get_vocabulary().index(word) == preds)and (text.split(word)[1]!=" "+word) :
            text = text + ' '+ word

            print(text)
            time.sleep(2)




1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


IndexError: list index out of range

In [29]:

token = vectorization('what is the fee')
padd_tokenized = pad_sequences([token], maxlen=max_len,padding='pre')

In [30]:
preds = model.predict(padd_tokenized)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


In [33]:
import numpy as np

In [34]:
print(np.argmax(preds))

15
